config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'home' => 'home#index'

  resources :tiles, only: [:index, :update, :new, :create]

  get "/auth/twitter/callback" => "sessions#create"

  get "/auth/github/callback" => "users#update"
  get 'github_auth' => 'home#github_initial_auth_request'
  get '/auth/github/callback/code' => 'home#github_token_request'
  get '/auth/github/callback/token' => 'home#github_token'

  get "/signout" => "sessions#destroy", :as => :signout
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :tile

  def as_json(options = {})
    { url: url, description: description }
  end
end

app/models/repo.rb
class Repo
  def initialize(github_token)
    @service = GithubService.new(github_token)
  end

  def all
    @service.repos.map { |repo| _build_object(repo) }
  end

  def all_names
    all.map { |repo| repo.name }
  end

  def repo_feed(repo)
    @service.repo_feed(repo)
  end

  def _build_object(data)
    begin
      OpenStruct.new(data)
    rescue NoMethodError => error
      redirect_to home_path
    end
  end
end

app/models/tile.rb
class Tile < ActiveRecord::Base
  belongs_to :user
  has_many :links

  accepts_nested_attributes_for :links, allow_destroy: true

  def as_json(options = {})
    {
      id: id,
      title: title,
      links: links
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tiles

  def self.find_or_create_from_auth(auth)
    user = User.find_or_create_by(provider: auth.provider, uid: auth.uid)
    user.provider = auth.provider
    user.uid      = auth.uid
    user.name     = auth.info.name
    # user.token    = auth.credentials.token
    user.save
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  helper JsonHelper

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tiles = current_user.tiles
    if current_user.github_token
      repo = Repo.new(current_user.github_token)
      @repos = repo.all
    end
  end

  def github_initial_auth_request
    auth_params = "?client_id=#{ENV["GITHUB_ID"]}&redirect_uri=http://localhost:3000/auth/github/callback/code"
    github_auth_url = "https://github.com/login/oauth/authorize/" + auth_params
    redirect_to github_auth_url
  end

  def github_token_request
    conn = Faraday.new("https://github.com")
    conn.headers = { "Accept" => "application/json" }
    conn.params  = { "client_id" => ENV["GITHUB_ID"],
                     "client_secret" => ENV["GITHUB_SECRET"],
                     "code" => params[:code]
    }
    responce = JSON.parse(conn.post("/login/oauth/access_token").body)
    current_user.github_token = responce["access_token"]
    redirect_to home_path
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    @user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to home_path, :notice => "Signed in!"
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to home_path, :notice => "Signed in!"
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

  def update
    user = User.find(params[:x])
  end
end

app/controllers/tiles_controller.rb
class TilesController < ApplicationController
  def index
    tiles = current_user.tiles.all
    render json: {
      tiles: tiles.map { |tile| tile.to_json }
    }
  end

  def new
    @tile = Tile.new
    @links = @tile.links.build
  end

  def create
    # require 'pry'; binding.pry
    @tile = Tile.new(tile_params)
    if @tile.save
      redirect_to home_path
    else
      render :new
    end
  end

  def update
    #tile = current_user.tiles.find(params[:id])
    # require 'pry'; binding.pry
    tile = Tile.find(params[:id])
    tile.update_attributes(tile_params)

    if tile.save
      render json: tile
    else
      # ...
    end
  end

  private

  def tile_params
    params[:links_attributes] ||= []
    params.require(:tile).permit(:title, links_attributes: [:id, :description, :url])
  end

  def link_params
    params.permit(:description, :url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/json_helper.rb
module JsonHelper
  def tiles_to_json(tiles)
    tiles.map do |tile|
      TileSerializer.new(tile, root: false).as_json
    end.to_json
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_menu.html.erb
<div class="contain-to-grid">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
      <h1><a href="#">Home Front</a></h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if current_user %>
          <i class="fi-social-github"></i>
          Welcome <%= current_user.name %>
          <%= link_to "Sign Out", signout_path %>
        <% else %>
          <li class="active"><%= link_to "Sign in with Twitter", "/auth/twitter" %></li>
        <% end %>
        <% if current_user && current_user.github_token.nil? %>
          <%= link_to "Github Feed", github_auth_path, :id => "li", :class => "active" %>
        <% end %>
      <!-- Left Nav Section -->
      <ul class="left">
        <li><a href="#">    </a></li>
      </ul>
    </section>
  </nav>
k</div>

app/views/application/_tile.html.erb
<div class="tile small-block-grid-2 medium-block-grid-3 large-block-grid-4">
  <%= tile.title %>
  <ul>
    <% tile.links.each do |link|  %>
      <li><%= link_to link.description, link.url %>
    <% end %>
  </ul>
</div>

app/views/home/github_auth.html.erb
<%= @github_resopnce %>

app/views/home/index.html.erb
<!-- Masonry Container -->
<div class="row">
  <div class="large-12 columns">
    <ul id="tile-board" class="small-block-grid-1 medium-block-grid-3 large-block-grid-4">
      <div class="row">
        <%= link_to "New Tile", new_tile_path %>
         <%# <% @tiles.each do |tile| %>
        <%#   <%= render partial: "tile", locals: { tile: tile } %>
        <%# <% end %>
      </div>
    </ul>
  </div>
</div>

<% content_for :before_javascript do %>
  <script>
    window.onRoutesInitialized = function () {
      HomeFront.initialTiles = <%= raw tiles_to_json(@tiles) %>
    }
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Home Front" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "menu" %>
    <%= yield %>
    <%= yield :before_javascript %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tiles/new.html.erb
<form>
<%= form_for @tile do |f| %>
  <div class="row">
    <div class="large-12 columns">
    <%= f.text_field :title, lable %>
    </div>
  </div>
  <div class="row">
    <div class="large-4 columns">
    <%= f.fields_for :links do |link| %>
      <%= link.text_field :description %>
      <%= link.text_field :url %>
    <% end %>
    </div>
    <%= f.submit %>
    <% end %>
  </div>
</form>

app/views/welcome/index.html.erb
<div class="row">
  <div class='home'>
    <h1>Home Front</h1>
  </div>
</div>
<div class="row">
  <div class='home-row'>
  </div>
</div>

<div class='row'>
  <div class="large-12 columns">
    <ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-4">
      <li>
        <img src="http://placehold.it/500x600&text=Item">
      </li>
      <li>
        <img src="http://placehold.it/500x600&text=Item">
      </li>
      <li>
        <img src="http://placehold.it/500x600&text=Item">
      </li>
      <li>
        <img src="http://placehold.it/500x600&text=Item">
      </li>
    </ul>
  </div>
</div>